# Generated by Django 3.2.6 on 2021-09-04 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('units', models.CharField(max_length=50, verbose_name='Единица измрения')),
            ],
            options={
                'verbose_name_plural': 'Компоненты',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1, verbose_name='Количество')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.component', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('diameter', models.IntegerField(null=True, verbose_name='Диаметр тортика')),
                ('weight', models.FloatField(null=True, verbose_name='Вес')),
                ('components', models.ManyToManyField(through='calculator.Ingredients', to='calculator.Component', verbose_name='Ингредиенты')),
            ],
            options={
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.AddField(
            model_name='ingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredients',
            unique_together={('recipe', 'component')},
        ),
    ]
