# Generated by Django 3.2.6 on 2021-09-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='form',
            field=models.CharField(choices=[('r', 'Круглая'), ('s', 'Квадратная'), ('p', 'Прямоугольная')], default='r', max_length=1, verbose_name='Форма'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instruction',
            field=models.TextField(null=True, verbose_name='Рецепт приготовления'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diameter',
            field=models.IntegerField(blank=True, default=20, null=True, verbose_name='Диаметр'),
        ),
    ]
