# Generated by Django 3.2.6 on 2021-09-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20210906_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='form',
            field=models.CharField(choices=[('c', 'Круглая'), ('s', 'Квадратная'), ('r', 'Прямоугольная')], default='r', max_length=1, verbose_name='Форма'),
        ),
    ]
