# Generated by Django 3.2.6 on 2021-09-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_recipe_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='annotation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredients',
            unique_together={('recipe', 'component', 'annotation')},
        ),
    ]
