# Generated by Django 3.2.6 on 2021-12-09 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculator', '0004_auto_20210914_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diameter',
            field=models.IntegerField(blank=True, null=True, verbose_name='Диаметр'),
        ),
        migrations.CreateModel(
            name='RecipeStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calculator.recipe')),
            ],
            options={
                'verbose_name_plural': 'Статистика просмотров',
            },
        ),
    ]
